/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coding;

/**
 *
 * @author Admin
 */
public class LINGKARAN extends javax.swing.JFrame {
    double jari,luas,keliling;

    /**
     * Creates new form LINGKARAN
     */
    public LINGKARAN() {
        initComponents();
        reset();
    }
    void reset (){
        JARIJARI.setText(null);
        ALUAS.setText(null);
        AKELILING.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JARIJARI = new javax.swing.JTextField();
        PKEMBALI = new javax.swing.JButton();
        PRESET = new javax.swing.JButton();
        PHITUNG = new javax.swing.JButton();
        ALUAS = new javax.swing.JLabel();
        AKELILING = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("LINGKARAN");

        jLabel2.setText("JARI-JARI");

        PKEMBALI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coding/arrow.png"))); // NOI18N
        PKEMBALI.setText("KEMBALI");
        PKEMBALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PKEMBALIActionPerformed(evt);
            }
        });

        PRESET.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coding/circular.png"))); // NOI18N
        PRESET.setText("RESET");
        PRESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRESETActionPerformed(evt);
            }
        });

        PHITUNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coding/account.png"))); // NOI18N
        PHITUNG.setText("HITUNG");
        PHITUNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PHITUNGActionPerformed(evt);
            }
        });

        ALUAS.setText("jLabel3");

        AKELILING.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(PHITUNG)
                            .addComponent(ALUAS)
                            .addComponent(AKELILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(JARIJARI, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(PRESET)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PKEMBALI)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JARIJARI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PKEMBALI)
                    .addComponent(PRESET)
                    .addComponent(PHITUNG))
                .addGap(42, 42, 42)
                .addComponent(ALUAS)
                .addGap(26, 26, 26)
                .addComponent(AKELILING)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PKEMBALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PKEMBALIActionPerformed
        new home ().setVisible(true);
        dispose();
    }//GEN-LAST:event_PKEMBALIActionPerformed

    private void PRESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRESETActionPerformed
        reset();
    }//GEN-LAST:event_PRESETActionPerformed

    private void PHITUNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PHITUNGActionPerformed
        jari = Double.parseDouble(JARIJARI.getText());
        luas = 3.14 * jari * jari;
        ALUAS.setText("LUAS : "+luas);
        AKELILING.setText("KELILING : "+keliling);
        
    }//GEN-LAST:event_PHITUNGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LINGKARAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LINGKARAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LINGKARAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LINGKARAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LINGKARAN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AKELILING;
    private javax.swing.JLabel ALUAS;
    private javax.swing.JTextField JARIJARI;
    private javax.swing.JButton PHITUNG;
    private javax.swing.JButton PKEMBALI;
    private javax.swing.JButton PRESET;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
